// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: image_embosser/image_embosser.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ImageEmbosser

/// Namespace containing generated types for the "ImageEmbosser" service.
public enum ImageEmbosser {
    /// Service descriptor for the "ImageEmbosser" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageEmbosser")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "EmbossImage" metadata.
        public enum EmbossImage {
            /// Request type for "EmbossImage".
            public typealias Input = EmbossImageRequest
            /// Response type for "EmbossImage".
            public typealias Output = EmbossImageResponse
            /// Descriptor for "EmbossImage".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageEmbosser"),
                method: "EmbossImage"
            )
        }
        /// Descriptors for all methods in the "ImageEmbosser" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            EmbossImage.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ImageEmbosser" service.
    public static let ImageEmbosser = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageEmbosser")
}

// MARK: ImageEmbosser (server)

extension ImageEmbosser {
    /// Streaming variant of the service protocol for the "ImageEmbosser" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "EmbossImage" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `EmbossImageRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `EmbossImageResponse` messages.
        func embossImage(
            request: GRPCCore.StreamingServerRequest<EmbossImageRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<EmbossImageResponse>
    }

    /// Service protocol for the "ImageEmbosser" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: ImageEmbosser.StreamingServiceProtocol {
        /// Handle the "EmbossImage" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `EmbossImageRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `EmbossImageResponse` message.
        func embossImage(
            request: GRPCCore.ServerRequest<EmbossImageRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<EmbossImageResponse>
    }

    /// Simple service protocol for the "ImageEmbosser" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: ImageEmbosser.ServiceProtocol {
        /// Handle the "EmbossImage" method.
        ///
        /// - Parameters:
        ///   - request: A `EmbossImageRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `EmbossImageResponse` to respond with.
        func embossImage(
            request: EmbossImageRequest,
            context: GRPCCore.ServerContext
        ) async throws -> EmbossImageResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
extension ImageEmbosser.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: ImageEmbosser.Method.EmbossImage.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<EmbossImageRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<EmbossImageResponse>(),
            handler: { request, context in
                try await self.embossImage(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension ImageEmbosser.ServiceProtocol {
    public func embossImage(
        request: GRPCCore.StreamingServerRequest<EmbossImageRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<EmbossImageResponse> {
        let response = try await self.embossImage(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension ImageEmbosser.SimpleServiceProtocol {
    public func embossImage(
        request: GRPCCore.ServerRequest<EmbossImageRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<EmbossImageResponse> {
        return GRPCCore.ServerResponse<EmbossImageResponse>(
            message: try await self.embossImage(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: ImageEmbosser (client)

extension ImageEmbosser {
    /// Generated client protocol for the "ImageEmbosser" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "EmbossImage" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `EmbossImageRequest` message.
        ///   - serializer: A serializer for `EmbossImageRequest` messages.
        ///   - deserializer: A deserializer for `EmbossImageResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func embossImage<Result>(
            request: GRPCCore.ClientRequest<EmbossImageRequest>,
            serializer: some GRPCCore.MessageSerializer<EmbossImageRequest>,
            deserializer: some GRPCCore.MessageDeserializer<EmbossImageResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<EmbossImageResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ImageEmbosser" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "EmbossImage" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `EmbossImageRequest` message.
        ///   - serializer: A serializer for `EmbossImageRequest` messages.
        ///   - deserializer: A deserializer for `EmbossImageResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func embossImage<Result>(
            request: GRPCCore.ClientRequest<EmbossImageRequest>,
            serializer: some GRPCCore.MessageSerializer<EmbossImageRequest>,
            deserializer: some GRPCCore.MessageDeserializer<EmbossImageResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<EmbossImageResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ImageEmbosser.Method.EmbossImage.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension ImageEmbosser.ClientProtocol {
    /// Call the "EmbossImage" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `EmbossImageRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embossImage<Result>(
        request: GRPCCore.ClientRequest<EmbossImageRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<EmbossImageResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.embossImage(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<EmbossImageRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<EmbossImageResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension ImageEmbosser.ClientProtocol {
    /// Call the "EmbossImage" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embossImage<Result>(
        _ message: EmbossImageRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<EmbossImageResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<EmbossImageRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.embossImage(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}