//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: embosser.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `EmbosserClient`, then call methods of this protocol to make API calls.
public protocol EmbosserClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: EmbosserClientInterceptorFactoryProtocol? { get }

  func embossImage(
    _ request: EmbossImageRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<EmbossImageRequest, EmbossImageResponse>
}

extension EmbosserClientProtocol {
  public var serviceName: String {
    return "Embosser"
  }

  /// Unary call to EmbossImage
  ///
  /// - Parameters:
  ///   - request: Request to send to EmbossImage.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func embossImage(
    _ request: EmbossImageRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<EmbossImageRequest, EmbossImageResponse> {
    return self.makeUnaryCall(
      path: EmbosserClientMetadata.Methods.embossImage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEmbossImageInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension EmbosserClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "EmbosserNIOClient")
public final class EmbosserClient: EmbosserClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: EmbosserClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: EmbosserClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the Embosser service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: EmbosserClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct EmbosserNIOClient: EmbosserClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: EmbosserClientInterceptorFactoryProtocol?

  /// Creates a client for the Embosser service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: EmbosserClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol EmbosserAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: EmbosserClientInterceptorFactoryProtocol? { get }

  func makeEmbossImageCall(
    _ request: EmbossImageRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<EmbossImageRequest, EmbossImageResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension EmbosserAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return EmbosserClientMetadata.serviceDescriptor
  }

  public var interceptors: EmbosserClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeEmbossImageCall(
    _ request: EmbossImageRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<EmbossImageRequest, EmbossImageResponse> {
    return self.makeAsyncUnaryCall(
      path: EmbosserClientMetadata.Methods.embossImage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEmbossImageInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension EmbosserAsyncClientProtocol {
  public func embossImage(
    _ request: EmbossImageRequest,
    callOptions: CallOptions? = nil
  ) async throws -> EmbossImageResponse {
    return try await self.performAsyncUnaryCall(
      path: EmbosserClientMetadata.Methods.embossImage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEmbossImageInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct EmbosserAsyncClient: EmbosserAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: EmbosserClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: EmbosserClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol EmbosserClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'embossImage'.
  func makeEmbossImageInterceptors() -> [ClientInterceptor<EmbossImageRequest, EmbossImageResponse>]
}

public enum EmbosserClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Embosser",
    fullName: "Embosser",
    methods: [
      EmbosserClientMetadata.Methods.embossImage,
    ]
  )

  public enum Methods {
    public static let embossImage = GRPCMethodDescriptor(
      name: "EmbossImage",
      path: "/Embosser/EmbossImage",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol EmbosserProvider: CallHandlerProvider {
  var interceptors: EmbosserServerInterceptorFactoryProtocol? { get }

  func embossImage(request: EmbossImageRequest, context: StatusOnlyCallContext) -> EventLoopFuture<EmbossImageResponse>
}

extension EmbosserProvider {
  public var serviceName: Substring {
    return EmbosserServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "EmbossImage":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<EmbossImageRequest>(),
        responseSerializer: ProtobufSerializer<EmbossImageResponse>(),
        interceptors: self.interceptors?.makeEmbossImageInterceptors() ?? [],
        userFunction: self.embossImage(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol EmbosserAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: EmbosserServerInterceptorFactoryProtocol? { get }

  func embossImage(
    request: EmbossImageRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> EmbossImageResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension EmbosserAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return EmbosserServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return EmbosserServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: EmbosserServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "EmbossImage":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<EmbossImageRequest>(),
        responseSerializer: ProtobufSerializer<EmbossImageResponse>(),
        interceptors: self.interceptors?.makeEmbossImageInterceptors() ?? [],
        wrapping: { try await self.embossImage(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol EmbosserServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'embossImage'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEmbossImageInterceptors() -> [ServerInterceptor<EmbossImageRequest, EmbossImageResponse>]
}

public enum EmbosserServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Embosser",
    fullName: "Embosser",
    methods: [
      EmbosserServerMetadata.Methods.embossImage,
    ]
  )

  public enum Methods {
    public static let embossImage = GRPCMethodDescriptor(
      name: "EmbossImage",
      path: "/Embosser/EmbossImage",
      type: GRPCCallType.unary
    )
  }
}
